### ISSUE TITLE
Related queries about this repository

### ISSUE THREAD

**Issue by ZWolken** [takinekotfs/CASIO-fx#8]
### Related queries about this repository

1. Does the repository holder own the copyright to the source code and resources in this repository?
2. If the repository owner does not own the copyright, then without discussing copyright ownership, is the source code in this repository hacked by the repository owner? If so, please provide proof of the process; if not, does the source provider give this repository owner permission to make it publicly available?
3. It is recommended that the repository owner should read the selected license (GNU General Public License v3.0) carefully before operating the repository.

**Also, hacking of the calculator ROM is a community-type operation, and repository holders are asked not to destroy the community for own personal purposes.**

**Comment by takinekotfs** [comment]
Ok, let me clear all of them:

1. Both yes and no. In fact, the original repository doesn't have any license or claim. I just updated the license in there: https://github.com/takinekotfs/CASIO-fx/commit/263e77a9e6a83750f6d6d09140f925238f25ebb6
2. I always commit while the author commits as the co-author. That means, your work is recorded.
3. Thanks for that. I just updated the license in the first question.

> Also, hacking of the calculator ROM is a community-type operation, and repository holders are asked not to destroy the community for own personal purposes.

Answer: Yes! It's a community-type operation, to which anyone has full access. But, be clearly that OSS in public repo is totally different from your personal project, where you can keep it privately.

**Comment by takinekotfs** [comment]
Anyways, @ZWolken , I recommend you to post this kind of questions in the [Discussion](https://github.com/takinekotfs/CASIO-fx/discussions).
